# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'know-your-flow' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for know-your-flow
  pod "Parse"
  pod "AlamofireImage"

  target 'know-your-flowTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'know-your-flowUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
